services:
  date:
    platform: linux/amd64
    image: galaxy4400/result-date
    build:
      context: .
      dockerfile: date.dockerfile

  result:
    platform: linux/amd64
    image: galaxy4400/result
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - date
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
